version: '3.7'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    environment:
      - node.name=single
      - cluster.name=standalone
      - discovery.type=single-node
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - gyun-bridge
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=["http://211.183.3.100:9200"]
    depends_on:
      - es
    networks:
      - gyun-bridge
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 3

  web:
    image: wordpress
    ports:
      - "8001-8009:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.labels.app == web]
    networks:
      - gyun-bridge

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    networks:
      - gyun-bridge
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.app == db]

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.7
    user: root
    deploy:
      replicas: 3
      placement:
        constraints: [node.labels.app == web]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ELASTICSEARCH_HOST=es
      - KIBANA_HOST=kibana
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    networks:
      - gyun-bridge
    configs:
      - source: mb_config
        target: /usr/share/metricbeat/metricbeat.yml

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.7
    user: root
    deploy:
      replicas: 3
      placement:
        constraints: [node.labels.app == web]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gyun-bridge
        #configs:
        #- source: fb_config
        #target: /usr/share/filebeat/filebeat.yml

volumes:
  data:
    driver: local

networks:
  gyun-bridge:
    driver: overlay

configs:
  mb_config:
    file: /home/user1/project_docker/metricbeat.yml
    # fb_config:
    #file: /home/user1/project_docker/filebeat.yml

