metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_locale:
      format: offset
  - add_host_metadata:
      netinfo.enabled: true

metricbeat.modules:
  - module: system
    metricsets: ["cpu", "load", "memory", "network", "process", "process_summary", "core", "diskio", "socket"]
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5
    period: 10s
    cpu.metrics:  ["percentages"]
    core.metrics: ["percentages"]

  - module: system
    period: 1m
    metricsets:
      - filesystem
      - fsstat
    processors:
    - drop_event.when.regexp:
        system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

  - module: system
    period: 15m
    metricsets:
      - uptime

  - module: docker
    metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

output.elasticsearch:
  hosts: ["http://211.183.3.100:9200"]  # Elasticsearch 호스트로 변경
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

setup.dashboards:
  enabled: true

setup.kibana:
  host: "http://211.183.3.100:5601"  # Kibana 호스트로 변경
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

  #xpack.monitoring:
  #enabled: true
  #elasticsearch:
  #  hosts: ["http://211.183.3.100:9200"]  # Elasticsearch 호스트로 변경
  #  username: ${ELASTICSEARCH_USERNAME}
  #  password: ${ELASTICSEARCH_PASSWORD}

