name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: manager

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy stack
      run: |
        docker stack deploy -c docker-compose.yml my_stack_name
